services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    PhpRbacBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Exception/'
            - '../src/Respository/'

    PhpRbacBundle\Repository\PermissionRepository:
        public: true
        arguments:
            $entityClass: '%php_rbac.resolve_target_entities.permission%'

    PhpRbacBundle\Repository\RoleRepository:
        public: true
        arguments:
            $entityClass: '%php_rbac.resolve_target_entities.role%'
